                    #while loop
"""
num =0
sum=0
n=#int(input('enter the number upto where the we want the sum of even numbers: '))
while num <= n:
    sum+=num
    num +=2
print('sum of even numbers is',sum)
"""

                    #For loop

"""
sum=0
n=int(input('enter the number upto where the we want the sum of even numbers: '))
for i in range(0,n+2,2):
    sum+=i
print(i,'sum of even numbers is',sum)
"""